### ISSUE TITLE
Ghidra Decompiler Error: No sleigh specification for x86:LE:64:default

### ISSUE THREAD

**Issue by Mladia** [radareorg/r2cutter#3]
**Environment information**
* Operating System: ArchLinux
* Cutter version: r2cutter 1:1.12.0-1
* Obtained from:
community repo arch

**Describe the bug**
I just updated the r2cutter, r2cutter and radare2 with pacman. After that I opened a project, which was before created with 4.2.2 radare2 cutter.
The Decompiler tab gives this error
Ghidra Decompiler Error: No sleigh specification for x86:LE:64:default

**Additional context**
When you just open the same file but as a new project, the same problem does not appear. I saved this project as a new one.
I managed to get everything working (and saving my old labels and everything) by modifying the "rc" config file in the project. I copied everything under functions from the old project to the new. One can probably get away just by modifying some file paths in "rc", but it was too much work at the moment for me.

**Comment by trufae** [comment]
This sounds like an issue in archlinux, also we dont fix bugs in old versions of r2/cutter, you may want to update the r2-5.1.0 as well as use r2ghidra and r2cutter. Afaik the archlinux maintainer is going thru updating all those packages and I didnt tagged any new release for r2cutter yet (will do as soon as the CI works again).

Im clsoing this issue because you should report this to the archlinux packaging, or try with newer packages of r2 (4.2 is 1 year old).

As a bonus hint.. can you use r2ghidra from the shell inside r2? because this error is there when the sleigh files are not installed so maybe the r2ghidrfa pkg is wrongly packaged.

Alternatively i would ask you to download the last builds available in the release page which ship r2, python and other interesting dependencies shipped inside a single bundle.
